[package]
name = "ship_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#TODO remove dynamic for release
bevy = "0.6.0"
rand = "0.7.3"
heron = { version = "2.0.1", features = ["2d"] }
